# === Bot Telegram ===
telegram.bot.token=8781421375:AAEr7yl_ffd-dHMlnQVLz-rBz7v08WhwvaU
telegram.bot.username=Bitel_Corp_bot

# === Servidor ===
server.port=8081

# === MySQL ===
spring.datasource.url=jdbc:mysql://localhost:3306/bot_db?useSSL=false&serverTimezone=America/Lima
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# === OpManager ===
opmanager.url=https://181.176.242.30

# Cookie COMPLETA copiada de DevTools → Network → Request Headers → Cookie
#opmanager.cookie=CountryName=PERU; signInAutomatically=true; JSESSIONID=83937C6A5800DB599FB44A74408E6E8E; NFA__SSO=C1F5A2340664EE09AE6F72FBF951600E; opmcsrfcookie=5336b3b9a8f4e81ac10226e1eb76754a14ad9a8d6f055b9c69e812186e8f1ed4d83f17887ff77114309efe00dd06c909649ce33af90965722cc0ebca9740a7aa; _zcsr_tmp=5336b3b9a8f4e81ac10226e1eb76754a14ad9a8d6f055b9c69e812186e8f1ed4d83f17887ff77114309efe00dd06c909649ce33af90965722cc0ebca9740a7aa

# X-ZCSRF-TOKEN (valor completo después de los dos puntos)
#opmanager.csrftoken=opmcsrftoken=5336b3b9a8f4e81ac10226e1eb76754a14ad9a8d6f055b9c69e812186e8f1ed4d83f17887ff77114309efe00dd06c909649ce33af90965722cc0ebca9740a7aa

# === OpManager ===

#pmanager.username=customer_pge
#opmanager.password=;H)[4DN9C)rju"@z